#pragma once

#define LIFE_POINTS 4

#define GRAVITY 20
#define FRICTION 0.85f

#define SPAWNERS_SPAWN_RATE 3 // In seconds
#define PUFFERFISH_HITS_BEFORE_DEATH 6
#define PUFFERFISH_SPEED 45
#define PUFFERFISH_MAX_SPEED_X 85
#define PUFFERFISH_MAX_SPEED_Y 250

#define PLAYER_SPEED 45
#define PLAYER_MAX_SPEED_X 170
#define PLAYER_MAX_SPEED_Y 190
#define PLAYER_JUMP_CD 0.5 // In seconds
#define PLAYER_JUMP_FORCE 2000
#define PLAYER_DAMAGE_CD 2 // In seconds
